import { WorkflowWithStructure, WorkflowNode, WorkflowEdge } from "./types";

const baseNodes = (workflowId: string): WorkflowNode[] => [
  {
    id: "node-trigger",
    workflow_id: workflowId,
    type: "TRIGGER",
    label: "Client inquiry received",
    description: "A prospect fills out the inquiry form for services.",
    position: { x: 120, y: 60 },
    metadata: {
      duration_minutes: 10,
      energy_level: "LOW",
      executor_type: "AGENT",
      assigned_agent: "ATTRACT",
      priority: "HIGH",
      preconditions: "Form connected to CRM",
      postconditions: "Lead record created",
      success_metrics: "Lead enriched with email and company",
      emotional_load_score: 2,
    },
  },
  {
    id: "node-qualify",
    workflow_id: workflowId,
    type: "DECISION",
    label: "Qualify lead",
    description: "Assess fit, urgency, and budget with quick rubric.",
    position: { x: 420, y: 80 },
    metadata: {
      duration_minutes: 20,
      energy_level: "MEDIUM",
      executor_type: "HUMAN",
      assigned_agent: "DEFINE",
      priority: "HIGH",
      preconditions: "Lead data available",
      postconditions: "Qualified lead updated",
      success_metrics: "Decision recorded in CRM",
      emotional_load_score: 3,
    },
  },
  {
    id: "node-onboard",
    workflow_id: workflowId,
    type: "TASK",
    label: "Send onboarding kit",
    description: "Share service overview, expectations, and kickoff survey.",
    position: { x: 720, y: 120 },
    metadata: {
      duration_minutes: 30,
      energy_level: "LOW",
      executor_type: "AGENT",
      assigned_agent: "SERVE",
      priority: "MEDIUM",
      preconditions: "Signed proposal",
      postconditions: "Client has access to portal",
      success_metrics: "Survey completed, portal login successful",
      emotional_load_score: 1,
    },
  },
  {
    id: "node-service",
    workflow_id: workflowId,
    type: "SUBFLOW",
    label: "Deliver core service",
    description: "Run the core engagement plan using templates.",
    position: { x: 1020, y: 160 },
    metadata: {
      duration_minutes: 240,
      energy_level: "HIGH",
      executor_type: "HUMAN",
      assigned_agent: "SERVE",
      priority: "HIGH",
      preconditions: "Kickoff meeting complete",
      postconditions: "Milestone delivered",
      success_metrics: "Milestone accepted by client",
      emotional_load_score: 4,
    },
  },
  {
    id: "node-retro",
    workflow_id: workflowId,
    type: "GOVERNANCE",
    label: "Governance retro",
    description: "Run a quick retro to capture learnings and risks.",
    position: { x: 1320, y: 200 },
    metadata: {
      duration_minutes: 45,
      energy_level: "MEDIUM",
      executor_type: "HUMAN",
      assigned_agent: "GOVERN",
      priority: "MEDIUM",
      preconditions: "Milestone delivered",
      postconditions: "Risks logged and actions assigned",
      success_metrics: "Two improvement items documented",
      emotional_load_score: 2,
    },
  },
  {
    id: "node-close",
    workflow_id: workflowId,
    type: "END",
    label: "Closeout & referral ask",
    description: "Wrap project, request testimonial, and ask for referrals.",
    position: { x: 1620, y: 240 },
    metadata: {
      duration_minutes: 40,
      energy_level: "LOW",
      executor_type: "AGENT",
      assigned_agent: "EVOLVE",
      priority: "MEDIUM",
      preconditions: "Project complete",
      postconditions: "Feedback captured and follow-up scheduled",
      success_metrics: "Testimonial collected and referral intro logged",
      emotional_load_score: 2,
    },
  },
];

const baseEdges = (workflowId: string): WorkflowEdge[] => [
  {
    id: "edge-trigger-qualify",
    workflow_id: workflowId,
    source_node_id: "node-trigger",
    target_node_id: "node-qualify",
    label: "New lead",
  },
  {
    id: "edge-qualify-onboard",
    workflow_id: workflowId,
    source_node_id: "node-qualify",
    target_node_id: "node-onboard",
    label: "Qualified",
  },
  {
    id: "edge-onboard-service",
    workflow_id: workflowId,
    source_node_id: "node-onboard",
    target_node_id: "node-service",
    label: "Ready",
  },
  {
    id: "edge-service-retro",
    workflow_id: workflowId,
    source_node_id: "node-service",
    target_node_id: "node-retro",
  },
  {
    id: "edge-retro-close",
    workflow_id: workflowId,
    source_node_id: "node-retro",
    target_node_id: "node-close",
  },
];

export const sampleWorkflowId = "workflow-sample-001";

export const sampleWorkflow: WorkflowWithStructure = {
  id: sampleWorkflowId,
  user_id: "user-sample",
  name: "Client Services Intake",
  description: "Handle inbound leads and deliver the first milestone for a services engagement.",
  phase: "SERVE",
  industry: "Consulting",
  status: "DRAFT",
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  nodes: baseNodes(sampleWorkflowId),
  edges: baseEdges(sampleWorkflowId),
};

export const sampleWorkflows: WorkflowWithStructure[] = [sampleWorkflow];
